(in-package #:shopper)

(defun main-navigation ()
  (with-html-output-to-string (s)
    ((:div :class "navbar")
     (:img :src "/images/banner.jpg")
     ((:div :class "nav-collapse collapse")
      ((:ul :class "nav nav-pills")
       ((:li :class "active")
	((:a :href "/") "Home"))
       (:li ((:a :href "#about") "About"))
       (:li ((:a :href "#contact") "Contact"))
       (str (featured-tags-nav))
       (str (tag-dropdown "More Chocolate!" (menu-tags)))
       (str (navigation-login))))
     (str (navigation-cart)))))

(defun navigation-login ()
  (if-let (user (hunchentoot:session-value :user))
    (with-html-output-to-string (s)
      (:li :class "divider-vertical")
	  (:li ((:a :href "/edit")
		"Edit"))
	  (:li ((:a :href "/logout")
		"Log out")))
    ""))

(defun featured-tags-nav ()
  (with-html-output-to-string (s)
    (dolist (tag-url (tag->nav (featured-tags)))
      (destructuring-bind (url . label) tag-url
	(htm (:li ((:a :href url)
		   (str label))))))))



(defun tag-dropdown (label tags)
  (with-html-output-to-string (s)
    ((:li :class "dropdown")
     ((:a :class "dropdown-toggle"
	  :data-toggle "dropdown"
	  :href "#")
      (str label)
      (:b :class "caret"))
     (str (nav-tabs (tag->nav tags) nil :class "dropdown-menu")))))

(defun navigation-cart ()
  (if-let ((store-open-p (store-open *web-store*))
	   (cart (get-cart)))
    (with-html-output-to-string (s)
      ((:a :href "/enter-details" :class "pull-right btn btn btn-primary")
       "CHECKOUT")
      ((:a :href "/shopping-cart" :class "pull-right btn btn-warning")
       (:i :class "icon-shopping-cart icon-white")
       (str (count-items-in cart))))
    ""))